FROM balenalib/%%BALENA_MACHINE_NAME%%-golang:latest-build AS build
WORKDIR /go/src/github.com/stayradiated/garage/app
COPY /app ./
RUN go get -v && go build

FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch
COPY --from=build /go/src/github.com/stayradiated/garage/app/ .
CMD ./app
